---
title: Raising the Role of Vocabulary Hubs for Semantic Data Interoperability in Dataspaces

abstract: |
  Dataspaces are an important enabler for industrial sharing data (either commercially licensed or private).
  Europe is investing heavily into sectoral dataspaces, federation and orchestration platforms like SIMPL, Eclipse DSC, GXFS, etc.
  Still, dataspaces enable shared data access, but do not solve the data interoperability problem.
  For that, the consumer would like to see the data from different providers in a harmonized and semantically integrated data.
  The Vocabulary Hub service (part of the IDSA RAM) provides a repository for ontologies and vocabularies.
  We describe an approach of raising the role of the vocabulary hub to also allow richer metadata description (e.g. the meaning of every column in a tabular dataset),
  and binding semantic descriptions to ingested datasets, thus providing on-the-fly data semantization and easing data querying.
  This is achieved through the integration of two commercial semantic products (PoolParty and GraphDB),
  leveraging the partnership between the Semantic Web Company and Ontotext,
  and is being developed within the frame of the Digital Europe project UNDERPIN,
  with applications to refinery and wind farm data.

author:
  - name: Robert David
    email: robert.david@semantic-web.com
    orcid: 0000-0002-3244-5341
    affiliation: 
     name: The Semantic Web Company
     country: Austria
  - name: Vladimir Alexiev
    email: vladimir.alexiev@ontotext.com
    orcid: 0000-0001-7508-7428
  - name: Petar Ivanov
    email: petar.ivanov@ontotext.com
    orcid: 0000-0001-8448-1005
    affiliation: 
      name: Ontotext
      country: Bulgaria
acm-metadata:
  keywords:
    - dataspaces
    - semantic interoperability
    - semantic technologies
    - ontologies
    - vocabulary hub
    - oil and gas
    - renewable energy
    - refineries
    - windfarms
  final: true
  # acmart-options: sigconf, review
  # copyright-year: 2024
  # acm-year: 2024
  copyright: acmcopyright
  # doi: 
  # conference-acronym: 
  # conference-name: 
  # conference-date: 
  # conference-location: 
  # isbn: 

format:
  acm-pdf:
    keep-tex: true 
bibliography: bibliography.bib

---

# Introduction
The European data economy heavily depends on the availability of data and the technological foundation to make use of it. 
Different industries and communities can benefit mutually by sharing data with each other, thereby supporting their digitization business goals.
Machine-learning systems heavily rely on high volumes of high-quality training data. 
Examples are the well-known mobility dataspace and use cases like energy communities for running simulations.
To cope with the challenge of data sharing, Dataspace approaches like the IDS RAM were introduced to not only solve the technical aspects of data sharing, 
but also to establish methods for data sovereignty so that dataspace participants can determine themselves how and when others can make use of their data.

For making use of shared data, interoperability is a crucial factor. 
While syntactic data exchange is well covered by clearly defined data formats, there is still the open challenge of semantic interoperability.
IDS RAM is firmly based on semantic metadata for all aspects and actors of a dataspace.
Furthermore, it can leverage semantic interoperability approaches through the Vocabulary Hub
that stores ontologies and semantic thesauri for data descriptions and can dereference URIs to provide semantic details of data assets.

In this paper, we present our proposal for a technological solution of an IDS Vocabulary Hub 
built on the integration of the GraphDB semantic graph database and PoolParty Semantic Suite. 
We not only cover the core Vocabulary Hub functionalities and responsibilities in a dataspace, 
but also extend the idea towards a Semantic Layer for dataspaces, 
which provides even more services to easily and semi-automatically manage semantic interoperability.
Thus we raise the role of the Vocabulary Hub to not only store semantic assets, 
but also to bind semantic descriptions dynamically to incoming data, 
therefore enabling richer discovery and semantic data integration between datasets.

# Projects and Use Cases
In the expanding data economy landscape supported by dataspaces, 
we are working on several projects which address practical data sharing needs and were we experience the importance of semantic interoperability to fulfill various use cases. 
Here we present 3 examples from the [DataBri-X](https://databri-x.eu/) and [UNDERPIN](https://underpinproject.eu/) projects that cover various application domains.

## Energy Dataspace
In this use case, we run simulations for energy communities, which predict the behavior of the energy grid. 
To provide precise predictions, there is the need of high amounts of example data. 
This data is of numeric type and different tabular data sources need to be semantically consolidated.

## Legal Dataspace
Analyzing documents in the legal domain is a highly challenging task because of the complexity of legal information. 
We provide recommender services for insights into corpora of legal documents
that identify the meaning via a legal knowledge graph, NLP analysis and semantic annotations.

## Manufacturing/Maintenance Dataspace
Operating refineries and wind farms involves high maintenance costs. 
Predicting potential failures and optimizing the maintenance operations to minimize the costs can be business-critical. 
For establishing predictive maintenance, we need high amounts of high quality training data
that can be obtained by data consolidation across different refinery and wind farm measurement sources. 

The UNDERPIN project addresses this problem by creating a dataspace for refineries, wind farms, and their equipment suppliers.
Extensive time series data is exchanged, but their format and meaning is not standardized.
Describing the meaning of these time series facilitates semantic interoperability between datasets from different providers.
This description includes measured variable, quantity kind and unit of measure,
which sensor took the measurements, what it is attached to, the detailed model and connectivity of that industrial equipment.

## The Problem
"Standard" dataspace solutions provide access to data, but do not typically address the data integration problem.
If a consumer wants to consume datasets from different providers in an integrated way, 
they need to harmonize the data to some common model, convert it, store it in a database, 
and potentially implement entity linking (correlation of different records that are about the same real-world thing) and data fusion.

Above we gave just 3 examples to illustrate the heterogeneity of data in the context of different use cases. 
We aim to develop solutions that not only fulfill the dataspace needs, 
but also improve the situation regarding semantic interoperability by providing services that can be easily leveraged to implement such use cases.

# Approach and IT-Solution
To tackle this problem, we introduce Semantic Web standards and technologies to model and process data. 
Vocabularies and ontologies (expressed using RDFS, OWL and SKOS) can represent data with a clear semantics based on standards. 
We leverage GraphDB and PoolParty as two software components that implement these standards to process the data.

## IDS Vocabulary Hub
IDSA defines the architecture of dataspaces in the reference architecture model IDS RAM. 
One of the defined architectural components, the Vocabulary Hub, has the role to provide vocabularies to annotate and describe data assets and services. 
These vocabularies form a common language to enable semantic interoperability among the dataspace participants. 
The Vocabulary Hub is responsible for resolving annotations of data assets and for providing details in the form of standardized semantic descriptions. 
It supports the use of Semantic Web standards for defining and representing RDF vocabularies and ontologies 
and thereby provides semantic interoperability in a standardized and machine-readable way.

## GraphDB Graph Database
TODO

## PoolParty Semantic Suite
PoolParty Semantic Suite is a semantic middleware platform based on W3C standards, specifically the Semantic Web, which provides a wide variety of functionality in the area of knowledge graph management, graph-based NLP, semantic search and recommender systems.

At the core of PoolParty is the Thesaurus Manager, which can be used to create and maintain RDF-based vocabularies, including ontologies, schemas and different kinds of knowledge models. These vocabularies can be applied for various use cases, from bridging data silos in enterprises by implementing data consolidation via the vocabularies, to annotating documents with semantic annotations to implement semantic search and recommendations which provide insights into data.

PoolParty is well suited to form the basis of a vocabulary management system within a dataspace, 
effectively implementing not only the Vocabulary Hub role, 
but also providing additional services that improve the expressiveness of common vocabularies and automate semantic interoperability.

## The GraphDB Poolparty Integration
The integration of GraphDB and PoolParty leverages synergies of a high-performance graph database with a platform for knowledge graph management.

Both GraphDb and PoolParty are based on W3C recommendations like RDF, OWL and SPARQL. They therefore seamlessly integrate with each other, but also with other services and components in dataspaces which support these machine-readable standards for semantic interoperability.

# A Semantic Solution and its Benefits
When harmonizing data, we need to provide a method to automatically map and process it,
so this can be done efficiently on large datasets and/or regular updates in dataspaces. 
The benefit provided should support the ML training in such a way that the consolidated dataset is exposed as uniform training dataset.

## Semantic Layer Approach
The Vocabulary Hub, as IDS defines it in the IDS-RAM, is a basic building block to achieve semantic interoperability in dataspaces by provisioning common vocabularies. 
We aim to go one step further and envision a Semantic Layer for dataspaces, 
which provides vocabulary-based services for advanced and automated semantic descriptions of metadata and data. 
The Semantic Layer is implemented as services based on the GraphDB and PoolParty and provided as a one seamlessly integrated component.

In the following, we discuss 
i) the services provided for the Vocabulary Hub component and 
ii) additional services as Vocabulary Hub extensions that implement a Semantic Layer for dataspaces.

Vocabulary Hub Services:
- RDF based: both GraphDB and PoolParty store and manage data based on the RDF data model. RDF is the basic building stone and underlying vocabulary definitions.
- Scalable vocabulary storage: cluster implementation for higher throughput and a fault tolerant architecture.
- Knowledge graph management: easy management of vocabularies using a rich web user interface and integration via Web APIs. 
  Vocabularies can be created and edited based on standards like RDFS, OWL and SKOS, and existing vocabularies can be reused and combined to fit specific dataspace needs.
- SPARQL service for semantic lookups: dereference URIs describing data assets to retrieve a semantic description of the entity from the graph database.

Semantic Layer Services support both unstructured and structured data assets:
- Unstructured data: semantic annotation services for documents based on concept tagging. 
  PoolParty’s KG-based NLP primarily uses SKOS taxonomies to identify concepts in documents, 
  but can be extended with OWL ontology elements (classes, properties) for increased expressiveness.
- Structured data: we support structured data harmonization methods, including semantic mapping and linking SKOS concepts
  - Ontology-Based Data Access (OBDA) is used for virtualization of relational data, i.e. accessing relational data as semantic data.
    It is well suited for semantic querying of large amounts of data, while keeping the original relational data in place (NoETL approach). 
    Ontologies are leveraged to construct the OBDA mapping; 
    they are governed via the Semantic Layer and can harmonize data assets of various formats using a precise mapping. 
    Furthermore, it can be used to establish a fine-grained access control, thereby deciding for individual data elements if they should be exposed ot not.
  - RDB to RDF Mapping Language (R2RML) [@souripriyadasR2RMLRDBRDF2012]
    and RDF Mapping Language (RML) [@RMLIntroduction2024]
    are intended for data transformation processes within a dataspace, 
    where the original source is used as a basis to create an RDF representation (ETL approach).
  - GraphDB supports both OBDA and R2RML through its integration of ONTOP [@bagosiOntopFrameworkOntology2014].
    The same mappings can be used for NoETL virtual data access, or for ETL (to materialize the semantic data).
  - CSV on the Web (CSVW) [@swirrlCSVWStandards2024] is a set of W3C standards 
    that allow detailed semantic description of tabular data using a JSON "manifest" file.
  - SKOS concepts are used for structured data in several ways. 
    Concepts can be directly added to RDF data via semantic links (properties from an ontology), 
    they can be used to annotate specific literals of an RDF graph,
    or they can be used to associate documents with (specific parts of) an RDF graph.
- Inference services: we provide metadata expansion services based on interlinked vocabularies in combination with ontologies. 
  This inference approach can be used with semantic tagging for unstructured data, as well as the structured data approaches.
  - Inference tagging is provided by a PoolParty tagging service in combination with an expansion query for implementing the inference. 
    The query can be configured to work for various scenarios.
- Vocabulary crosswalks are a data modeling approach using interlinks to relate:
  - Different vocabularies from similar or the same domain that cover different areas or aspects of the domain. 
    By relating concepts with each other using 1:1, 1:n and m:n relations, we can automatically expand queries and annotations by traversing the interlinked graph.
  - Different versions of the same vocabulary to automatically translate between those versions.
- Metadata inference based on interlinked vocabularies is similar to crosswalks, 
  but intended to represent different levels of abstraction, 
  so that we are able to infer from a more general vocabulary to a more specific vocabulary and vice versa. 
  For example, we can start with DCAT themes vocabularies and link to further vocabularies, which are more specific for certain areas or which go into more detail.

## Architecture and Implementation

# Conclusion and Future Work
We presented an approach for dynamically binding dataspace datasets
We have implemented a first prototype of our approach. 

The next steps include:
- Bringing it into an actual dataspace in practice, representing and integrating datasets from different dataspace participants.
- Implementing use cases for richer discoverability and harmonized querying.
Also, the ML should actually benefit regarding quality in practice, which still needs to be verified.

# Acknowledgements
This work is partially supported by the Digital Europe programme project [UNDERPIN](https://underpinproject.eu/) (grant agreement 101123179)

# References
